name: CI

env:
  project: 'release-go'

on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: go build ./...
    - name: Test
      run: go test ./...
