name: ci

on: [push, pull_request]

env:
  project: 'release-go'

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]

        # include:
        #   - go-version: [1.15.x]
        #     os: [ubuntu-latest]
        #   - go-version: [1.15.x]
        #     os: [macos-latest]
        #   - go-version: [1.15.x]
        #     os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Install
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...

    - name: Upload
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.project }}_${{ matrix.os }}_${{ matrix.go-version }}
        path: |
          ${{ env.project }}
          ${{ env.project }}.exe

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Archives
        run: find artifacts -mindepth 1 -maxdepth 1  -exec tar -C {} -cvzf {}.tgz . \;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
